### ISSUE TITLE
MyFaces Dependencies Wrong

### ISSUE THREAD

**Issue by melloware** [rmpestano/quarkus-omnifaces#4] opened 2020-06-02 14:06 UTC
I am following your instructions but can't get it to build.
2 things.

1. I think MyFaces changed the locaton of the runtime and deployment jars.

https://search.maven.org/search?q=myfaces-quarkus

2. They released 2.3-next-M2 which you should be using instead of SNAPSHOT.

Can you update so I can try again?

**Comment by rmpestano** [comment] 2020-06-02 15:34
Hi, for now you need to build latest myfaces from master branch. It is not mentioned on readme because this repo used a released version of myfaces

**Comment by melloware** [comment] 2020-06-02 15:37
Yes but it looks like the Maven coordinates are completely different than what you have.  Is Maven Central wrong or is the SNAPSHOT correct?

You have...
```xml
<artifactId>myfaces-quarkus</artifactId>
```
but in Maven Central its..
```xml
<artifactId>myfaces-quarkus-runtime</artifactId>
```

**Comment by rmpestano** [comment] 2020-06-02 16:10
Hi @melloware, it is the right artifactId, look into [quarkus-myfaces here](https://github.com/apache/myfaces/blob/741c2dfd701eed5f0cf4ce79ba6d9ced5dc6b80a/extensions/quarkus/showcase/pom.xml#L55). 

What's the error are you facing?

**Comment by melloware** [comment] 2020-06-02 16:11
When I try to run with M2 which was just released last month your app doesn't work at all and says it can't find it.  THat is why I am surprised the SNAPSHOT works.

**Comment by melloware** [comment] 2020-06-02 16:15
For example just change...
```xml
<myfaces.version>2.3-next-SNAPSHOT</myfaces.version>
```
to
```xml
<myfaces.version>2.3-next-M2</myfaces.version>
```

Whichis from April 20th and I can't get your app to build at all

**Comment by rmpestano** [comment] 2020-06-02 16:24
Yes, quarkus myfaces changed since latest release, It's to be compliance with other quarkus extensions

**Comment by melloware** [comment] 2020-06-02 16:27
Ahh OK.  Rathe rthan me download all this code to build these SNAPSHOTS can you just try my latest commit here:
https://github.com/omnifaces/omnifaces/pull/557/files

I changed it from using the servletcontext to just using the classloader to look for "META-INF/web.xml"

**Comment by rmpestano** [comment] 2020-06-03 07:08
Just confirmed the fix is working on the PR, I'll close this issue. 

Thanks!

**Closed by rmpestano** 2020-06-03 07:08 UTC

**Comment by melloware** [comment] 2020-06-03 11:04
No problem.  Although one other thing. when I did get a build running it looked like a lot of artifacts wanted to be checked into GitHub.  A lot of them were /target artificates so I am wondering if your .gitignore is quite right?  I am running on Windows 10 if that matters.

**Comment by rmpestano** [comment] 2020-06-03 14:19
For now I'm running on macos and ubuntu, I see nothing to commit on target, maybe windows related to windows, if you find a pattern that works for you we can add to gitignore
